// Run: node test.js  (starts temporary servers with their own databases)
const os = require('os'), path = require('path'), fs = require('fs'), { spawn } = require('child_process');
const P1 = 3900 + Math.floor(Math.random() * 40), P2 = P1 + 50, tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'wisp-'));
const start = (port, env) => spawn('node', ['server.js'], { env: { ...process.env, PORT: port, DATA_DIR: path.join(tmp, '' + port), ...env }, stdio: ['ignore', 'pipe', 'ignore'] });
const s1 = start(P1, { ADMIN_ID: 'testadmin', ADMIN_KEY: 'TestPass-12345', TRUST_PROXY: '1' }), s2 = start(P2, { ADMIN_CONFIG: '/nonexistent' });
const client = port => { let ck = ''; return async (m, u, b, hdr = true, xh = {}) => {
  const r = await fetch(`http://localhost:${port}${u}`, { method: m, headers: { 'Content-Type': 'application/json', ...(hdr ? { 'X-Requested-With': 'wisp' } : {}), cookie: ck, ...xh }, body: b ? JSON.stringify(b) : undefined });
  const sc = r.headers.get('set-cookie'); if (sc) ck = sc.split(';')[0]; let j = {}; try { j = await r.json(); } catch {} return { s: r.status, j }; }; };
let pass = 0, fail = 0; const ok = (n, c) => { c ? pass++ : fail++; console.log((c ? '  ✓ ' : '  ✗ ') + n); };
const APP = { ign: 'ProKing', uid: '555111', game: 'Free Fire', role: 'Nader', igl: 'Yes', mobile: '9876543210', age: '19', exp: 'KD 4.2' };
(async () => {
  await new Promise(r => setTimeout(r, 900));
  const g = client(P1), adm = client(P1), usr = client(P1); let r;
  console.log('Public site & security');
  r = await g('GET', '/api/c/games'); ok('guest reads seeded games', r.s === 200 && r.j.items.length > 0);
  r = await g('GET', '/api/c/news'); ok('news + achievements are public', r.s === 200 && (await g('GET', '/api/c/ach')).s === 200);
  r = await g('GET', '/api/c/payments'); ok('payouts hidden from guests', r.s === 401);
  r = await g('GET', '/api/c/apps'); ok('applications (mobile numbers) hidden from guests', r.s === 401);
  r = await g('PUT', '/api/c/games/x', { n: 'x' }, false); ok('missing CSRF header blocked', r.s === 403);
  console.log('Admin ID + password');
  r = await adm('POST', '/api/login', { email: 'testadmin', password: 'wrong' }); ok('wrong admin password rejected', r.s === 401);
  r = await adm('POST', '/api/login', { email: 'testadmin', password: 'TestPass-12345' }); ok('login form accepts the admin ID + password', r.s === 200 && r.j.user.role === 'admin');
  ok('admin can edit (settings saved)', (await adm('PUT', '/api/c/settings/main', { name: 'Wisp Division', trials: 'open' })).s === 200);
  r = await usr('POST', '/api/register', { name: 'Ravi', email: 'ravi@x.com', password: 'longenough1' }); ok('sign up gives pending user', r.s === 201 && r.j.user.role === 'pending');
  ok('normal users cannot edit site content', (await usr('PUT', '/api/c/games/x', { n: 'x' })).s === 403); ok('separate admin-login endpoint is removed', (await usr('POST', '/api/admin/login', { id: 'x', password: 'y' })).s === 404);
  console.log('Trial application');
  r = await g('PUT', '/api/c/apps/WD-AAAAA', { ...APP, mobile: '12345' }); ok('invalid mobile number rejected', r.s === 400);
  r = await g('PUT', '/api/c/apps/WD-AB12C', { ...APP, role: 'Hacker', status: 'Selected', note: 'self-selected' }); ok('guest can apply', r.s === 200);
  r = await g('PUT', '/api/c/apps/WD-AB12C', APP); ok('cannot overwrite an application', r.s === 409);
  r = await adm('GET', '/api/c/apps/WD-AB12C'); const A = r.j.item;
  ok('role limited to Rusher/Secondary Rusher/Nader/Sniper', A.role === 'Rusher'); ok('IGL + mobile saved, status forced Pending', A.igl === 'Yes' && A.mobile === '9876543210' && A.status === 'Pending' && A.note === '');
  r = await g('GET', '/api/c/results'); const row = r.j.items.find(x => x.name === 'ProKing');
  ok('public board shows applicant as Pending', row && row.status === 'Pending'); ok('public board hides IDs and mobile numbers', !('id' in row) && !JSON.stringify(r.j).includes('9876543210'));
  console.log('Declaring results (public, with reason)');
  r = await adm('PUT', '/api/c/apps/WD-AB12C', { ...A, status: 'Selected', note: '' }); ok('result without a reason is refused', r.s === 400);
  await adm('PUT', '/api/c/apps/WD-AB12C', { ...A, status: 'Selected', note: 'Strong aim and great game sense' });
  await adm('PUT', '/api/c/results/WD-AB12C', { name: 'ProKing', game: 'Free Fire', role: 'Nader', status: 'Selected', note: 'Strong aim and great game sense', at: Date.now() });
  r = await g('GET', '/api/c/results/WD-AB12C'); ok('applicant sees Selected + reason by ID', r.j.item.status === 'Selected' && /aim/.test(r.j.item.note));
  r = await adm('PUT', '/api/c/results/WD-AB12C', { name: 'ProKing', status: 'Not Selected', note: 'Needs more scrim experience' }); ok('"Not Selected" status accepted', r.s === 200 && (await g('GET', '/api/c/results/WD-AB12C')).j.item.status === 'Not Selected');
  console.log('Official-site features');
  await adm('PUT', '/api/c/settings/main', { name: 'Wisp Division', trials: 'closed', about: 'We play.' });
  r = await g('PUT', '/api/c/apps/WD-ZZ999', APP); ok('applications blocked while trials are closed', r.s === 403);
  await adm('PUT', '/api/c/settings/main', { name: 'Wisp Division', trials: 'open' });
  r = await adm('POST', '/api/c/news', { title: 'Big win', body: 'We won', date: '2026-10-08', pin: 'yes' }); ok('admin posts news', r.s === 200 && (await g('GET', '/api/c/news')).j.items.some(n => n.title === 'Big win'));
  r = await g('POST', '/api/c/messages', { name: 'Fan', contact: 'f@x.com', msg: 'Hello team' }); ok('visitor can send a contact message', r.s === 200);
  ok('only admin can read messages', (await g('GET', '/api/c/messages')).s === 401 && (await adm('GET', '/api/c/messages')).j.items.length === 1);
  console.log('Roles');
  const uid = (await adm('GET', '/api/c/users')).j.items.find(x => x.email === 'ravi@x.com').id;
  ok('admin accounts are not listed for editing', !(await adm('GET', '/api/c/users')).j.items.some(x => x.role === 'admin'));
  ok('role "admin" cannot be granted', (await adm('PUT', '/api/c/users/' + uid, { role: 'admin' })).s === 400);
  await adm('PUT', '/api/c/users/' + uid, { role: 'member' }); ok('approved member reads payouts', (await usr('GET', '/api/c/payments')).s === 200);
  console.log('Behind a proxy (Render)');
  const ipA = { 'X-Forwarded-For': '9.9.9.1' }, ipB = { 'X-Forwarded-For': '9.9.9.2' }; let last;
  for (let i = 0; i < 6; i++) last = await g('PUT', '/api/c/apps/WD-RL00' + i, { ign: '', uid: '' }, true, ipA);
  ok('one noisy visitor gets rate-limited', last.s === 429); ok('other visitors are not blocked by them', (await g('PUT', '/api/c/apps/WD-RL009', { ign: '', uid: '' }, true, ipB)).s === 400);
  console.log('First-run setup (no admin configured)');
  const g2 = client(P2); let code = ''; s2.stdout.on('data', d => { const m = /Setup code: (\w+)/.exec(d); if (m) code = m[1]; });
  await new Promise(r => setTimeout(r, 300));
  ok('site asks for admin setup', (await g2('GET', '/api/setup')).j.needed === true);
  ok('wrong setup code rejected', (await g2('POST', '/api/setup', { code: 'nope', id: 'boss', password: 'LongPassword1' })).s === 403);
  ok('short admin password rejected', (await g2('POST', '/api/setup', { code, id: 'boss', password: 'short' })).s === 400);
  r = await g2('POST', '/api/setup', { code, id: 'boss', password: 'LongPassword1' }); ok('admin created with chosen ID + password', r.s === 201 && r.j.user.role === 'admin');
  ok('setup cannot run twice', (await g2('POST', '/api/setup', { code, id: 'x1234', password: 'LongPassword1' })).s === 409);
  console.log(`\n${pass} passed, ${fail} failed`); s1.kill(); s2.kill();
  setTimeout(() => { try { fs.rmSync(tmp, { recursive: true, force: true }); } catch {} process.exit(fail ? 1 : 0); }, 500);
})();
